apiVersion: v1
kind: Namespace
metadata:
  name: retry
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-ingester
  namespace: retry
spec:
  selector:
    matchLabels:
      app: post-ingester
  template:
    metadata:
      labels:
        app: post-ingester
    spec:
      containers:
      - name: post-ingester
        image: ghcr.io/dadjeibaah/post-ingester:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: post-ingester
  namespace: retry
spec:
  selector:
    app: post-ingester
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-cooker
  namespace: retry
spec:
  selector:
    matchLabels:
      app: slow-cooker
  template:
    metadata:
      labels:
        app: slow-cooker
    spec:
      containers:
      - name: slow-cooker
        image: ghcr.io/dadjeibaah/slow_cooker:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: post-ingester.retry.svc.cluster.local
  namespace: retry
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /api/post
    name: POST /api/post